# docker-compose.yml

version: "3"

services:
  api:
    networks:
      - proxynet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./upload/images/:/app/upload/images/"
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production

networks:
  proxynet:
    name: custom_network2